### ISSUE TITLE
After activating the CNIC SSL Addon, I didn't see any products 

### ISSUE THREAD

**Issue by jsjcjsjc** [centralnic-reseller/whmcs-ssl#114]
**Context (please complete the following information):**
 - OS: windows 11
 - Browser edge
 - WHMCS Version 8.13
 - PHP Version 7.4
 - ISPAPI SSL Module Version [v11.0.1]
https://centralnic-reseller.github.io/centralnic-reseller/docs/cnic/whmcs/whmcs-ssl/#automatic-product-import--pricing-sync

Hi
After activating the CNIC SSL Addon, I didn't see any products 
And I didn't see how to enter my RRP account
[![vzCgWF.jpg](https://s1.ax1x.com/2022/09/15/vzCgWF.jpg)](https://imgse.com/i/vzCgWF)
Thanks in advance

**Comment by KaiSchwarz-cnic** [comment]
Hi again @jsjcjsjc !

Well, for the SSL Addon, you need one of the below Registrar Modules
* HEXONET (ispapi) 
* RRPproxy (keysystems) 

If they are in use (installed, activated) and your credentials are entered there, well done! We are relying on these registrar modules to connect to the underlying API endpoints and to do the API Communication.

Initially you don't see products, yes. You have to import the prices / products / product group in the Admin Area of our Addon.
So, activating the checkboxes as shown in your screenshot and then clicking on the blue Import Button.

Not sure, if I understood you correctly, is the List of SSL Products to import already empty?
If so, do you mind providing your account name?

**Comment by jsjcjsjc** [comment]
> 

Thanks for your kind help.
I  think i know the reason, I have to remove TestMode in RRP modules,then it works

**Comment by KaiSchwarz-cnic** [comment]
Sounds Good! Enjoy!
